/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_edd2;

import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    static Main f = new Main();
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_Campos = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        B_CrearCampo = new javax.swing.JButton();
        B_ListarCampo = new javax.swing.JButton();
        B_ModificarCampo = new javax.swing.JButton();
        B_BorrarCampo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDialog_CrearCampos = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel_CrearCampo = new javax.swing.JLabel();
        jLabel_CrearCampo1 = new javax.swing.JLabel();
        Nombre_Campo = new javax.swing.JTextField();
        jLabel_CrearCampo2 = new javax.swing.JLabel();
        cb_TD = new javax.swing.JComboBox<>();
        jLabel_CrearCampo3 = new javax.swing.JLabel();
        jLabel_CrearCampo4 = new javax.swing.JLabel();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        spinnerS = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog_EditarCampos = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel_CrearCampo5 = new javax.swing.JLabel();
        jLabel_CrearCampo6 = new javax.swing.JLabel();
        Nombre_Campo1 = new javax.swing.JTextField();
        jLabel_CrearCampo7 = new javax.swing.JLabel();
        cb_TD1 = new javax.swing.JComboBox<>();
        jLabel_CrearCampo8 = new javax.swing.JLabel();
        jLabel_CrearCampo9 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        No1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel_CrearCampo10 = new javax.swing.JLabel();
        Cb_editarCampo = new javax.swing.JComboBox<>();
        jSpinner2 = new javax.swing.JSpinner();
        jDialog_BorrarCampo = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        B_Eliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jDialog_Archivo = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        B_NuevoArchivo = new javax.swing.JButton();
        B_AbrirArchivo = new javax.swing.JButton();
        B_GuardarArchivo = new javax.swing.JButton();
        B_CerrarArchivo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jd_registro = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Nombre_Campo2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        B_Campo = new javax.swing.JButton();
        B_Registro = new javax.swing.JButton();
        B_Index = new javax.swing.JButton();
        B_Exportar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 46, 452, 240));

        B_CrearCampo.setBackground(new java.awt.Color(255, 255, 255));
        B_CrearCampo.setText("Crear Campo");
        B_CrearCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CrearCampoActionPerformed(evt);
            }
        });
        jPanel2.add(B_CrearCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 126, -1));

        B_ListarCampo.setBackground(new java.awt.Color(255, 255, 255));
        B_ListarCampo.setText("Listar Campos");
        B_ListarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ListarCampoActionPerformed(evt);
            }
        });
        jPanel2.add(B_ListarCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 126, -1));

        B_ModificarCampo.setBackground(new java.awt.Color(255, 255, 255));
        B_ModificarCampo.setText("Modificar Campo");
        B_ModificarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ModificarCampoActionPerformed(evt);
            }
        });
        jPanel2.add(B_ModificarCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        B_BorrarCampo.setBackground(new java.awt.Color(255, 255, 255));
        B_BorrarCampo.setText("Borrar Campo");
        B_BorrarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BorrarCampoActionPerformed(evt);
            }
        });
        jPanel2.add(B_BorrarCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 126, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background2.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 400));

        javax.swing.GroupLayout jDialog_CamposLayout = new javax.swing.GroupLayout(jDialog_Campos.getContentPane());
        jDialog_Campos.getContentPane().setLayout(jDialog_CamposLayout);
        jDialog_CamposLayout.setHorizontalGroup(
            jDialog_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
            .addGroup(jDialog_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog_CamposLayout.setVerticalGroup(
            jDialog_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
            .addGroup(jDialog_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_CrearCampo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_CrearCampo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CrearCampo.setText("Crear Campo");
        jPanel3.add(jLabel_CrearCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel_CrearCampo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_CrearCampo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CrearCampo1.setText("Nombre del Campo");
        jPanel3.add(jLabel_CrearCampo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 73, -1, -1));

        Nombre_Campo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nombre_Campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_CampoActionPerformed(evt);
            }
        });
        jPanel3.add(Nombre_Campo, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 73, 260, -1));

        jLabel_CrearCampo2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_CrearCampo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CrearCampo2.setText("Tipo de Dato");
        jPanel3.add(jLabel_CrearCampo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, -1, -1));

        cb_TD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "String", "Char", "Int" }));
        jPanel3.add(cb_TD, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 109, 120, -1));

        jLabel_CrearCampo3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_CrearCampo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CrearCampo3.setText("Numero de caracteres máximo");
        jPanel3.add(jLabel_CrearCampo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 154, -1, -1));

        jLabel_CrearCampo4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_CrearCampo4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CrearCampo4.setText("¿Es llave primaria? ");
        jPanel3.add(jLabel_CrearCampo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 199, -1, -1));

        RB1.setBackground(new java.awt.Color(204, 0, 204));
        buttonGroup1.add(RB1);
        RB1.setForeground(new java.awt.Color(255, 255, 255));
        RB1.setText("Sí");
        jPanel3.add(RB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 197, -1, -1));

        RB2.setBackground(new java.awt.Color(204, 0, 204));
        buttonGroup1.add(RB2);
        RB2.setForeground(new java.awt.Color(255, 255, 255));
        RB2.setText("No");
        jPanel3.add(RB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 197, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear Campo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));
        jPanel3.add(spinnerS, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 153, 54, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background2.jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 370));

        javax.swing.GroupLayout jDialog_CrearCamposLayout = new javax.swing.GroupLayout(jDialog_CrearCampos.getContentPane());
        jDialog_CrearCampos.getContentPane().setLayout(jDialog_CrearCamposLayout);
        jDialog_CrearCamposLayout.setHorizontalGroup(
            jDialog_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
            .addGroup(jDialog_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog_CrearCamposLayout.setVerticalGroup(
            jDialog_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
            .addGroup(jDialog_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 102, 51));

        jLabel_CrearCampo5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_CrearCampo5.setText("Editar campo");

        jLabel_CrearCampo6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_CrearCampo6.setText("Nombre del Campo");

        Nombre_Campo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nombre_Campo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_Campo1ActionPerformed(evt);
            }
        });

        jLabel_CrearCampo7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_CrearCampo7.setText("Tipo de Dato");

        cb_TD1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "String", "Char", "Int" }));

        jLabel_CrearCampo8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_CrearCampo8.setText("Numero de caracteres máximo");

        jLabel_CrearCampo9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_CrearCampo9.setText("¿Es llave primaria? ");

        jRadioButton2.setBackground(new java.awt.Color(255, 102, 51));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Sí");

        No1.setBackground(new java.awt.Color(255, 102, 51));
        buttonGroup1.add(No1);
        No1.setText("No");

        jButton2.setText("Modificar Campo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel_CrearCampo10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_CrearCampo10.setText("Campo a Editar");

        Cb_editarCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel_CrearCampo6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel_CrearCampo5))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(cb_TD1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Nombre_Campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel_CrearCampo7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_CrearCampo10)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Cb_editarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel_CrearCampo9)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jRadioButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(No1))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel_CrearCampo8)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel_CrearCampo5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_CrearCampo6)
                            .addComponent(Nombre_Campo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel_CrearCampo10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cb_editarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CrearCampo7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_TD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CrearCampo8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CrearCampo9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2)
                    .addComponent(No1))
                .addGap(72, 72, 72)
                .addComponent(jButton2)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jDialog_EditarCamposLayout = new javax.swing.GroupLayout(jDialog_EditarCampos.getContentPane());
        jDialog_EditarCampos.getContentPane().setLayout(jDialog_EditarCamposLayout);
        jDialog_EditarCamposLayout.setHorizontalGroup(
            jDialog_EditarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
            .addGroup(jDialog_EditarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog_EditarCamposLayout.setVerticalGroup(
            jDialog_EditarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
            .addGroup(jDialog_EditarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 102, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 143, 36));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Campo a Eliminar");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        B_Eliminar.setBackground(new java.awt.Color(255, 255, 255));
        B_Eliminar.setText("Eliminar");
        B_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EliminarActionPerformed(evt);
            }
        });
        jPanel5.add(B_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 143, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background2.jpg"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 660, 290));

        javax.swing.GroupLayout jDialog_BorrarCampoLayout = new javax.swing.GroupLayout(jDialog_BorrarCampo.getContentPane());
        jDialog_BorrarCampo.getContentPane().setLayout(jDialog_BorrarCampoLayout);
        jDialog_BorrarCampoLayout.setHorizontalGroup(
            jDialog_BorrarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_BorrarCampoLayout.setVerticalGroup(
            jDialog_BorrarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 102, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B_NuevoArchivo.setBackground(new java.awt.Color(255, 255, 255));
        B_NuevoArchivo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        B_NuevoArchivo.setText("Nuevo Archivo");
        jPanel6.add(B_NuevoArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 176, 35));

        B_AbrirArchivo.setBackground(new java.awt.Color(255, 255, 255));
        B_AbrirArchivo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        B_AbrirArchivo.setText("Abrir archivo");
        jPanel6.add(B_AbrirArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 176, 35));

        B_GuardarArchivo.setBackground(new java.awt.Color(255, 255, 255));
        B_GuardarArchivo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        B_GuardarArchivo.setText("Guardar Archivo");
        jPanel6.add(B_GuardarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 176, 35));

        B_CerrarArchivo.setBackground(new java.awt.Color(255, 255, 255));
        B_CerrarArchivo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        B_CerrarArchivo.setText("Guardar Archivo");
        jPanel6.add(B_CerrarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 176, 35));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background2.jpg"))); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, 0, 660, 400));

        javax.swing.GroupLayout jDialog_ArchivoLayout = new javax.swing.GroupLayout(jDialog_Archivo.getContentPane());
        jDialog_Archivo.getContentPane().setLayout(jDialog_ArchivoLayout);
        jDialog_ArchivoLayout.setHorizontalGroup(
            jDialog_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
            .addGroup(jDialog_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog_ArchivoLayout.setVerticalGroup(
            jDialog_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
            .addGroup(jDialog_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Escriba Campo");

        Nombre_Campo2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nombre_Campo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_Campo2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("LLenar Campo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_registroLayout = new javax.swing.GroupLayout(jd_registro.getContentPane());
        jd_registro.getContentPane().setLayout(jd_registroLayout);
        jd_registroLayout.setHorizontalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(Nombre_Campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jd_registroLayout.setVerticalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Nombre_Campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 700));

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("File Manager");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        Titulo1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("Standard");
        jPanel1.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        B_Campo.setBackground(new java.awt.Color(255, 255, 255));
        B_Campo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        B_Campo.setText("Campos");
        B_Campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CampoActionPerformed(evt);
            }
        });
        jPanel1.add(B_Campo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 160, 50));

        B_Registro.setBackground(new java.awt.Color(255, 255, 255));
        B_Registro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        B_Registro.setText("Archivo");
        B_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RegistroActionPerformed(evt);
            }
        });
        jPanel1.add(B_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 160, 50));

        B_Index.setBackground(new java.awt.Color(255, 255, 255));
        B_Index.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        B_Index.setText("Index");
        B_Index.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_IndexActionPerformed(evt);
            }
        });
        jPanel1.add(B_Index, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 160, 50));

        B_Exportar.setBackground(new java.awt.Color(255, 255, 255));
        B_Exportar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        B_Exportar.setText("Exportar");
        B_Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ExportarActionPerformed(evt);
            }
        });
        jPanel1.add(B_Exportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 160, 50));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Registro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 160, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background2.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 0, 700, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_ListarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ListarCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_ListarCampoActionPerformed

    private void B_ModificarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ModificarCampoActionPerformed
        jDialog_EditarCampos.pack();
        jDialog_EditarCampos.setLocationRelativeTo(this);
        jDialog_EditarCampos.setVisible(true);
    }//GEN-LAST:event_B_ModificarCampoActionPerformed

    private void B_BorrarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BorrarCampoActionPerformed
        jDialog_BorrarCampo.pack();
        jDialog_BorrarCampo.setLocationRelativeTo(this);
        jDialog_BorrarCampo.setVisible(true);
    }//GEN-LAST:event_B_BorrarCampoActionPerformed

    private void Nombre_CampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_CampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_CampoActionPerformed

    private void B_CrearCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CrearCampoActionPerformed
        jDialog_CrearCampos.pack();
        jDialog_CrearCampos.setLocationRelativeTo(this);
        jDialog_CrearCampos.setVisible(true);
    }//GEN-LAST:event_B_CrearCampoActionPerformed

    private void Nombre_Campo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_Campo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_Campo1ActionPerformed

    private void B_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_EliminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void B_ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_ExportarActionPerformed

    private void B_IndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_IndexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_IndexActionPerformed

    private void B_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RegistroActionPerformed
        jDialog_Archivo.pack();
        jDialog_Archivo.setLocationRelativeTo(this);
        jDialog_Archivo.setVisible(true);
    }//GEN-LAST:event_B_RegistroActionPerformed

    private void B_CampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CampoActionPerformed
        jDialog_Campos.pack();
        jDialog_Campos.setLocationRelativeTo(this);
        jDialog_Campos.setVisible(true);
    }//GEN-LAST:event_B_CampoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String name=Nombre_Campo.getText();
            String tipo="";
            if(cb_TD.getSelectedIndex()==0){
                tipo="String";
            }
            if(cb_TD.getSelectedIndex()==1){
                tipo="Char";
            }
            if(cb_TD.getSelectedIndex()==2){
                tipo="int";
            }
            int size=(Integer)spinnerS.getValue();
            boolean llave;
            if(RB1.isSelected()){
                llave=true;
            }else{
                llave=false;
            }
            Campos c1=new Campos(name,tipo,size,llave);
            
            JOptionPane.showMessageDialog(this, "Creado Excitosamente");
            System.out.println(c1.toString());
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error al crear");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Nombre_Campo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_Campo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_Campo2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jd_registro.pack();
        jd_registro.setLocationRelativeTo(this);
        jd_registro.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
        }catch(Exception e){
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                f.setExtendedState(MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_AbrirArchivo;
    private javax.swing.JButton B_BorrarCampo;
    private javax.swing.JButton B_Campo;
    private javax.swing.JButton B_CerrarArchivo;
    private javax.swing.JButton B_CrearCampo;
    private javax.swing.JButton B_Eliminar;
    private javax.swing.JButton B_Exportar;
    private javax.swing.JButton B_GuardarArchivo;
    private javax.swing.JButton B_Index;
    private javax.swing.JButton B_ListarCampo;
    private javax.swing.JButton B_ModificarCampo;
    private javax.swing.JButton B_NuevoArchivo;
    private javax.swing.JButton B_Registro;
    private javax.swing.JComboBox<String> Cb_editarCampo;
    private javax.swing.JRadioButton No1;
    private javax.swing.JTextField Nombre_Campo;
    private javax.swing.JTextField Nombre_Campo1;
    private javax.swing.JTextField Nombre_Campo2;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_TD;
    private javax.swing.JComboBox<String> cb_TD1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog_Archivo;
    private javax.swing.JDialog jDialog_BorrarCampo;
    private javax.swing.JDialog jDialog_Campos;
    private javax.swing.JDialog jDialog_CrearCampos;
    private javax.swing.JDialog jDialog_EditarCampos;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_CrearCampo;
    private javax.swing.JLabel jLabel_CrearCampo1;
    private javax.swing.JLabel jLabel_CrearCampo10;
    private javax.swing.JLabel jLabel_CrearCampo2;
    private javax.swing.JLabel jLabel_CrearCampo3;
    private javax.swing.JLabel jLabel_CrearCampo4;
    private javax.swing.JLabel jLabel_CrearCampo5;
    private javax.swing.JLabel jLabel_CrearCampo6;
    private javax.swing.JLabel jLabel_CrearCampo7;
    private javax.swing.JLabel jLabel_CrearCampo8;
    private javax.swing.JLabel jLabel_CrearCampo9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JDialog jd_registro;
    private javax.swing.JSpinner spinnerS;
    // End of variables declaration//GEN-END:variables
}
